//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Web.Services.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing message part &apos;{0}&apos; for message &apos;{1}&apos; from namespace &apos;{2}&apos;..
        /// </summary>
        internal static string MissingMessagePartForMessageFromNamespace3 {
            get {
                return ResourceManager.GetString("MissingMessagePartForMessageFromNamespace3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only objects of type OperationInput or OperationOutput may be added..
        /// </summary>
        internal static string OnlyOperationInputOrOperationOutputTypes {
            get {
                return ResourceManager.GetString("OnlyOperationInputOrOperationOutputTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only XmlElements or types deriving from ServiceDescriptionFormatExtension may be added..
        /// </summary>
        internal static string OnlyXmlElementsOrTypesDerivingFromServiceDescriptionFormatExtension0 {
            get {
                return ResourceManager.GetString("OnlyXmlElementsOrTypesDerivingFromServiceDescriptionFormatExtension0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required XmlFormatExtension attribute is missing on class {0}..
        /// </summary>
        internal static string RequiredXmlFormatExtensionAttributeIsMissing1 {
            get {
                return ResourceManager.GetString("RequiredXmlFormatExtensionAttributeIsMissing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The syntax of type {0} may not be extended..
        /// </summary>
        internal static string TheSyntaxOfTypeMayNotBeExtended1 {
            get {
                return ResourceManager.GetString("TheSyntaxOfTypeMayNotBeExtended1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught in {0}.\r\n    {1}: {2}.
        /// </summary>
        internal static string TraceExceptionCaught {
            get {
                return ResourceManager.GetString("TraceExceptionCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Details:\r\n{0}.
        /// </summary>
        internal static string TraceExceptionDetails {
            get {
                return ResourceManager.GetString("TraceExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find definition for {0}.  Service Description with namespace {1} is missing..
        /// </summary>
        internal static string WebDescriptionMissing {
            get {
                return ResourceManager.GetString("WebDescriptionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element {0} named {1} from namespace {2} is missing..
        /// </summary>
        internal static string WebDescriptionMissingItem {
            get {
                return ResourceManager.GetString("WebDescriptionMissingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than one input and one output message may be specified..
        /// </summary>
        internal static string WebDescriptionTooManyMessages {
            get {
                return ResourceManager.GetString("WebDescriptionTooManyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one binding named &apos;{0}&apos; was specified. Each binding must have a unique name..
        /// </summary>
        internal static string WebDuplicateBinding {
            get {
                return ResourceManager.GetString("WebDuplicateBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one fault binding named &apos;{0}&apos; was specified. Each fault binding must have a unique name..
        /// </summary>
        internal static string WebDuplicateFaultBinding {
            get {
                return ResourceManager.GetString("WebDuplicateFaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one format extension named &apos;{0}&apos; was specified. Each format extension must have a unique name..
        /// </summary>
        internal static string WebDuplicateFormatExtension {
            get {
                return ResourceManager.GetString("WebDuplicateFormatExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one import named &apos;{0}&apos; was specified. Each import must have a unique name..
        /// </summary>
        internal static string WebDuplicateImport {
            get {
                return ResourceManager.GetString("WebDuplicateImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one message named &apos;{0}&apos; was specified. Each message must have a unique name..
        /// </summary>
        internal static string WebDuplicateMessage {
            get {
                return ResourceManager.GetString("WebDuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one message part named &apos;{0}&apos; was specified. Each message part must have a unique name..
        /// </summary>
        internal static string WebDuplicateMessagePart {
            get {
                return ResourceManager.GetString("WebDuplicateMessagePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one operation named &apos;{0}&apos; was specified. Each operation must have a unique name..
        /// </summary>
        internal static string WebDuplicateOperation {
            get {
                return ResourceManager.GetString("WebDuplicateOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one operation binding named &apos;{0}&apos; was specified. Each operation binding must have a unique name..
        /// </summary>
        internal static string WebDuplicateOperationBinding {
            get {
                return ResourceManager.GetString("WebDuplicateOperationBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one operation fault named &apos;{0}&apos; was specified. Each operation fault must have a unique name..
        /// </summary>
        internal static string WebDuplicateOperationFault {
            get {
                return ResourceManager.GetString("WebDuplicateOperationFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one operation message named &apos;{0}&apos; was specified. Each operation message must have a unique name..
        /// </summary>
        internal static string WebDuplicateOperationMessage {
            get {
                return ResourceManager.GetString("WebDuplicateOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one port named &apos;{0}&apos; was specified. Each port must have a unique name..
        /// </summary>
        internal static string WebDuplicatePort {
            get {
                return ResourceManager.GetString("WebDuplicatePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one port type named &apos;{0}&apos; was specified. Each port type must have a unique name..
        /// </summary>
        internal static string WebDuplicatePortType {
            get {
                return ResourceManager.GetString("WebDuplicatePortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one service named &apos;{0}&apos; was specified. Each service must have a unique name..
        /// </summary>
        internal static string WebDuplicateService {
            get {
                return ResourceManager.GetString("WebDuplicateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one service description with targetNamespace &apos;{0}&apos; was specified..
        /// </summary>
        internal static string WebDuplicateServiceDescription {
            get {
                return ResourceManager.GetString("WebDuplicateServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one {0} named &apos;{1}&apos; was specified. Each {0} must have a unique name..
        /// </summary>
        internal static string WebDuplicateUnknownElement {
            get {
                return ResourceManager.GetString("WebDuplicateUnknownElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for &apos;{0}&apos; cannot be negative..
        /// </summary>
        internal static string WebNegativeValue {
            get {
                return ResourceManager.GetString("WebNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element was not expected in this context: {0}..
        /// </summary>
        internal static string WebUnknownElement {
            get {
                return ResourceManager.GetString("WebUnknownElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected element was encountered: {0}. No elements were expected in this scope..
        /// </summary>
        internal static string WebUnknownElement1 {
            get {
                return ResourceManager.GetString("WebUnknownElement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element was not expected in this context: {0}. Expected elements: {1}..
        /// </summary>
        internal static string WebUnknownElement2 {
            get {
                return ResourceManager.GetString("WebUnknownElement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {0} Line {1}, position {2}..
        /// </summary>
        internal static string WsdlInstanceValidationDetails {
            get {
                return ResourceManager.GetString("WsdlInstanceValidationDetails", resourceCulture);
            }
        }
    }
}
